# -*- coding: utf-8 -*-
"""PSO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7WXJRTrDtO3Zwn5vhlpblf-VCohnnuG

**Portafolio PSO**
"""

! pip install yfinance
! pip install numpy
! pip install pandas
! pip install matplotlib
! pip install pyswarms

import numpy as np #Manejar datos y matrices
import pandas as pd
import yfinance as yf #obtener los datos financieros
import matplotlib.pyplot as plt # Graficas
from pyswarms.single.global_best import GlobalBestPSO # Poder utilizar el algoritmo PSO

# Deinir fechas y Activos.
start_date = "2023-04-01"
end_date = "2025-04-01"
tickers = ['KO', 'MSFT', 'NVDA', 'PFE', 'WMT', 'BTC-USD']

# Primero obtenemos los datos utilizando yahoo finance, verificar disponibilidad de datos y tomar preico de cierre de cada activo "Close"

data = yf.download(tickers, start=start_date, end=end_date)
print("Columnas disponibles en los datos:")
print(data.columns)
prices = data['Close']

# Cálculo de rendimientos diarios.
returns = prices.pct_change().dropna()

# Estadísticas descriptivas de los rendimientos
mean_returns = returns.mean()
volatility = returns.std()

# Rendimientos promedio y volatilidades
rendimientos_tabla = pd.DataFrame({
    'Rendimiento Promedio (%)': mean_returns * 100,
    'Volatilidad (%)': volatility * 100
})
print("\nEstadísticas del Portafolio:")
print(rendimientos_tabla)

# Matriz de Covarianza
cov_matrix = returns.cov()

print("\nMatriz de Covarianza:")
print(cov_matrix)

#Rendimiento promedio anualizado
mean_returns_anualizados = returns.mean() * 252

# Riesgo (volatilidad) anualizado
volatility = returns.std() * np.sqrt(252)

#Cov anualiado
cov_matrix_anualizada = cov_matrix * 252

print("\nRendimiento Promedio Anualizado:")
print(mean_returns_anualizados)

print("\nRiesgo (Volatilidad) Anualizado:")
print(volatility)

print("\nMatriz de Covarianza Anualizada:")
print(cov_matrix_anualizada)

# Función objetivo para PSO: minimizar -retorno*(1-λ) + λ*riesgo

def objetivo(weights, mu, cov, lambda_):
    weights = weights / np.sum(weights)
    retorno = np.dot(weights, mu) # mu es rendimiento de cada activo.
    riesgo = np.sqrt(np.dot(weights.T, np.dot(cov, weights)))
    return -retorno*(1-lambda_) + lambda_ * riesgo

#lambda es el peso que le damos al riesgo, dependiendo de lo adverso al riesgo, siendo 0, no importa el reisgo, .5 de igual importancia y 1 si es muy conservador.

# Envoltorio para PSO (muchas partículas)
def f(x):
    n_particles = x.shape[0]
    resultados = []
    for i in range(n_particles):
        w = x[i]
        w = w / np.sum(w)  # normalización
        resultados.append(objetivo(w, mean_returns_anualizados, cov_matrix_anualizada, lambda_=.6))
    return np.array(resultados)

#Aplica la función objetivo a todas las partículas del enjambre

# Configurar el algoritmo:

n_assets = len(tickers)
bounds = (np.zeros(n_assets), np.ones(n_assets))
options = {'c1': 1.5, 'c2': 1.5, 'w': .7}

# n_assets = numero de activos.
#Bounds = cada peso esa entre 0 y 1

#options:
#Modificar el coeficiente intelectual, social o velocidad de la particula.

#Ejecutar el PSO con 100 particulas en 500 iteraciones

optimizer = GlobalBestPSO(n_particles=100, dimensions=n_assets, options=options, bounds=bounds)
best_cost, best_pos = optimizer.optimize(f, iters=500)

#Normalizar parámetro para que sume 1 y ver el rendimiento y riesgo real

best_weights = best_pos / np.sum(best_pos)

# Rendimiento y riesgo anualizados del portafolio
port_return_anual = np.dot(best_weights, mean_returns * 252)
port_risk_anual = np.sqrt(np.dot(best_weights.T, np.dot(cov_matrix * 252, best_weights)))

# Imprimir resultados
print("\n--- Resultados del Portafolio Óptimo ---")
for t, w in zip(tickers, best_weights):
    print(f"{t}: {w:.2%}")

print(f"\nRendimiento esperado anualizado: {port_return_anual:.2%}")
print(f"Riesgo (desviación estándar anual): {port_risk_anual:.2%}")

# Gráfico de pesos
plt.figure(figsize=(8,5))
plt.bar(tickers, best_weights)
plt.title('Pesos Óptimos del Portafolio')
plt.ylabel('Proporción del capital')
plt.grid(axis='y')
plt.tight_layout()
plt.show()

# Cálculo del Índice de sharpe con este portafolio en México.
tasa_libre_de_riesgo = 0.09

sharpe_ratios = (port_return_anual - tasa_libre_de_riesgo) / port_risk_anual

print("Índice de Sharpe del portafolio:")
print(sharpe_ratios)

if sharpe_ratios > 1:
    print("El portafolio tiene un rendimiento superior que justifica el riesgo.")
elif sharpe_ratios < 1:
    print("El portafolio tiene un rendimiento inferior que no justifica el riesgo.")
else:
    print("El portafolio tiene un rendimiento aceptable ajustado al riesgo .")